dimensionality_reduction:
  umap:
    n_neighbors: [ 10, 20 ]
    #    n_components: [ 5, 10 ]
    min_dist: [ 0.0, 0.1, 0.3 ]
    metric: [ cosine, euclidean ]

clustering:
  kmeans:
    k_start: 3
    k_end: 50
  hdbscan:
    min_cluster_size: [ 15, 20, 30, 40, 50 ]
    min_samples: [ 10, 15, 20, 30, 40 ]
    #    metric: [ euclidean, manhattan, infinity ]
    cluster_selection_method: [ eom, leaf ]
    cluster_selection_epsilon: [ 0.0, 0.5, 0.7 ]
#    alpha: [ 1.0, 1.2 ]